/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PksZadanie;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mathis
 */
public class AnalyserGUI extends javax.swing.JFrame {

    private Integer arpTabExists = null;
    private Integer icmpTabExists = null;
    private Integer httpTabExists = null;
    private Integer httpsTabExists = null;
    private Integer ftpcTabExists = null;
    private Integer sshTabExists = null;
    private Integer ftpdTabExists = null;
    private Integer telnetTabExists = null;
    private File pcapFile;
    private JTabbedPane jTabbedPane4;
    private JTabbedPane jTabbedPane5;
    private JTabbedPane jTabbedPane6;
    private JTabbedPane jTabbedPane7;
    private JTabbedPane jTabbedPane8;
    private JTabbedPane jTabbedPane9;
    private JTabbedPane jTabbedPane10;
    private JTabbedPane jTabbedPane11;
    
    

    public AnalyserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChoose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));

        fileChoose.setText("Choose file");
        fileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseActionPerformed(evt);
            }
        });

        jLabel1.setText("Pcap file Analyser");

        jTabbedPane1.setVisible(false);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1260, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1260, 600));
        jTabbedPane1.addTab("tab1", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChoose)
                .addGap(418, 418, 418))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fileChoose))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("only .pcap", "pcap"));
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                System.out.println("You chose to open this directory: "
                        + chooser.getSelectedFile().getAbsolutePath());
                pcapFile = chooser.getSelectedFile();
                AnalyserMainCheck panel = new AnalyserMainCheck(pcapFile, this);
                jTabbedPane1.addTab("MainCheck", jTabbedPane3);
                jTabbedPane3.addTab(pcapFile.getName(), panel);
                jTabbedPane3.addTab("Scan Result", panel.getAn().getResult());
                if (panel.getAn().getArpPanel() != null) {

                    if (arpTabExists == null) {
                        jTabbedPane4 = new JTabbedPane();
                        jTabbedPane1.addTab("ARP", jTabbedPane4);
                        arpTabExists = 1;
                    }
                    jTabbedPane4.addTab(pcapFile.getName(), panel.getAn().getArpPanel());
                }

                if (panel.getAn().getIcmpPanel() != null) {
                    if (icmpTabExists == null) {
                        jTabbedPane5 = new JTabbedPane();
                        jTabbedPane1.addTab("ICMP", jTabbedPane5);
                        icmpTabExists = 1;
                    }
                    jTabbedPane5.addTab(pcapFile.getName(), panel.getAn().getIcmpPanel());
                }
                if(panel.getAn().getHttpPanel() != null){
                    if(httpTabExists == null){
                        jTabbedPane6 = new JTabbedPane();
                        jTabbedPane1.addTab("HTTP", jTabbedPane6);
                        httpTabExists = 1;
                    }
                    jTabbedPane6.addTab(pcapFile.getName(), panel.getAn().getHttpPanel());
                }
                if(panel.getAn().getHttpsPanel() != null){
                    if(httpsTabExists == null){
                        jTabbedPane7 = new JTabbedPane();
                        jTabbedPane1.addTab("HTTPS", jTabbedPane7);
                        httpsTabExists = 1;
                    }
                    jTabbedPane7.addTab(pcapFile.getName(), panel.getAn().getHttpsPanel());
                }
                
                if(panel.getAn().getFtpcPanel() != null){
                    if(ftpcTabExists == null){
                        jTabbedPane8 = new JTabbedPane();
                        jTabbedPane1.addTab("FTP-c",jTabbedPane8);
                        ftpcTabExists = 1;
                    }
                    jTabbedPane8.addTab(pcapFile.getName(), panel.getAn().getFtpcPanel());
                }
                if(panel.getAn().getSshPanel()!= null){
                    if(sshTabExists == null){
                        jTabbedPane9 = new JTabbedPane();
                        jTabbedPane1.addTab("SSH",jTabbedPane9);
                        sshTabExists = 1;
                    }
                    jTabbedPane9.addTab(pcapFile.getName(), panel.getAn().getSshPanel());
                }
                if(panel.getAn().getFtpdPanel()!= null){
                    if(ftpdTabExists == null){
                        jTabbedPane10 = new JTabbedPane();
                        jTabbedPane1.addTab("FTP-d",jTabbedPane10);
                        ftpdTabExists = 1;
                    }
                    jTabbedPane10.addTab(pcapFile.getName(), panel.getAn().getFtpdPanel());
                }
                if(panel.getAn().getTelnetPanel()!= null){
                    if(telnetTabExists == null){
                        jTabbedPane11 = new JTabbedPane();
                        jTabbedPane1.addTab("Telnet",jTabbedPane11);
                        telnetTabExists = 1;
                    }
                    jTabbedPane11.addTab(pcapFile.getName(), panel.getAn().getTelnetPanel());
                }
                jTabbedPane1.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AnalyserGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_fileChooseActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // AnalyzerGUI gui = new AnalyzerGUI();
                // AnalyzerGuiController guicontroller = new AnalyzerGuiController();
                new AnalyserGUI().setVisible(true);
            }
        });
    }

    public File getPcapFile() {
        return pcapFile;
    }

    public JButton getFileChoose() {
        return fileChoose;
    }

    public JTabbedPane getjTabbedPane3() {
        return jTabbedPane3;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
