/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PksZadanie;

import PksZadanie.equip.TcpCommunication;
import PksZadanie.equip.Frame;
import PksZadanie.equip.TcpCommunicationDataUpdater;
import PksZadanie.equip.TcpParserDataUpdater;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import pkszadanie.analysers.Analyser;

/**
 *
 * @author Mathis
 */
public class AnalyserTcpParserPanel extends javax.swing.JPanel {

   private Analyser an;
   private ArrayList<Frame> typeList;
   private TcpCommunication comm;
    public AnalyserTcpParserPanel(Analyser an,TcpCommunication comm) {
        this.an = an;
        this.typeList = comm.getList();
        
        this.comm = comm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDataText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tcpMainTable = new javax.swing.JTable();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(940, 600));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Frame Id", "SourceIp ", "DestinationIp", "Source Port", "Destination Port", "Flags", "Source MAC", "Destination MAC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.setName(""); // NOI18N
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
        }

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Length", "Frame count"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(940, 530));

        jDataText.setEditable(false);
        jDataText.setColumns(20);
        jDataText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jDataText.setRows(5);
        jDataText.setToolTipText("");
        jDataText.setName("Frame Data"); // NOI18N
        jScrollPane4.setViewportView(jDataText);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(940, 530));

        tcpMainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Communication Id", "Protocol ", "SourceIp ", "Source Port", "DestinationIp", "Destination Port", "Completed", "Frame count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcpMainTable.setColumnSelectionAllowed(true);
        tcpMainTable.setName(""); // NOI18N
        tcpMainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcpMainTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tcpMainTable);
        tcpMainTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tcpMainTable.getColumnModel().getColumnCount() > 0) {
            tcpMainTable.getColumnModel().getColumn(0).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(1).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(2).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(3).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(4).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(5).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(6).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(7).setResizable(false);
            tcpMainTable.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tcpMainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcpMainTableMouseClicked
        jDialog1.setVisible(true);
        jDialog1.setSize(1350, 650);
        jDialog1.setTitle("data from " + an.getPcap().getAbsolutePath() + " frame no. " + (tcpMainTable.getSelectedRow() + 1));
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);
        DefaultTableModel tableModel1 = (DefaultTableModel) jTable3.getModel();
        tableModel1.setRowCount(0);
        TcpCommunicationDataUpdater communicationSetter = new TcpCommunicationDataUpdater(typeList.get(tcpMainTable.getSelectedRow()), this);
    }//GEN-LAST:event_tcpMainTableMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jDialog2.setVisible(true);
        jDialog2.setSize(950, 650);
        jDialog2.setAlwaysOnTop(true);
        jDialog2.setTitle("data from " + an.getPcap().getAbsolutePath() + " frame no. " + (jTable2.getSelectedRow() + 1));
        TcpParserDataUpdater dataSetter = new TcpParserDataUpdater((Frame) comm.getComList().get(typeList.get(tcpMainTable.getSelectedRow()).getComId()).getTcpCommList().get(jTable2.getSelectedRow()), this);
        dataSetter.update();
    }//GEN-LAST:event_jTable2MouseClicked

    public Analyser getAn() {
        return an;
    }

    public JTextArea getjDataText() {
        return jDataText;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public JTable getjTable3() {
        return jTable3;
    }

    public TcpCommunication getComm() {
        return comm;
    }

    public JTable getTcpMainTable() {
        return tcpMainTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jDataText;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tcpMainTable;
    // End of variables declaration//GEN-END:variables
}
